LR: 0.001
alpha_initial: 1.0
alpha_lr: 0.001
alpha_optimizer: adam
batch_size: 128
buffer_capacity: 1000000
critic_grad_norm_clip: null
critic_hidden_act: relu
critic_hidden_num: 2
critic_hidden_size: 256
critic_lr: 0.001
critic_optimizer: adam
env: Ant-v2
eval_freq: 20
eval_size: 10000
eval_video_fps: 10
eval_video_freq: -1
eval_video_length: 200
eval_video_size:
- 200
- 200
gamma: 0.99
gpu: true
gpu_id: null
max_path_length_eval: 1000
max_path_length_train: 1000
min_buffer_size: 10000
num_epochs: 500
num_samples_per_epoch: 1000
num_train_steps_per_epoch: 1500
path: data/sac/ant
policy_grad_norm_clip: null
policy_hidden_act: relu
policy_hidden_num: 2
policy_hidden_size: 256
policy_lr: 0.001
policy_optimizer: adam
save_freq: 100
seed: 3708543239
target_entropy: null
target_update_freq: 1
target_update_tau: 0.005
train_alpha: true
