LR: 0.0003
WIDTH: 300
alpha_initial: 0.1
alpha_lr: 0.0003
alpha_optimizer: adam
batch_size: 128
buffer_capacity: 10000000
clf_enc_dim: 5
clf_enc_hidden_num: 0
clf_enc_hidden_size: 64
clf_grad_norm_clip: null
clf_hidden_act: relu
clf_hidden_num: 1
clf_hidden_size: 128
clf_lr: 0.0003
clf_optimizer: adam
comment: null
critic_grad_norm_clip: null
critic_hidden_act: relu
critic_hidden_num: 2
critic_hidden_size: 300
critic_lr: 0.0003
critic_optimizer: adam
env: HalfCheetah-v2
eval_freq: 100
eval_size: 1000
eval_video_fps: 20
eval_video_freq: 1
eval_video_length: 100
eval_video_size:
- 200
- 200
expert_data: demo/sac_cheetah/expert_data.pkl
expert_data_size: null
gamma: 0.99
gpu: true
gpu_id: 2
log_freq: 1
max_path_length_eval: 1000
max_path_length_train: 1000
min_buffer_size: 10000
num_epochs: 10000
num_samples_per_epoch: 1000
num_skills: 50
num_train_steps_per_epoch: 1000
path: data/new/diayn_enc/cheetah_d10_e5_clf1
policy_grad_norm_clip: null
policy_hidden_act: relu
policy_hidden_num: 2
policy_hidden_size: 300
policy_lr: 0.0003
policy_num_components: 4
policy_optimizer: adam
save_freq: 100
seed: 354743794
target_entropy: null
target_update_freq: 1
target_update_tau: 0.01
train_alpha: false
